gateway:
  class: istio
  name: api
  listeners:
    api:
      hostName:
  geoCode: 

tlsIssuer:
  email:
  privateKeySecretRef: le-staging
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  solvers:
    route53:
      hostedZoneID:
      region:
      accessKeyIDSecretRef:
        key: AWS_ACCESS_KEY_ID
        name: 
      secretAccessKeySecretRef:
        key: AWS_SECRET_ACCESS_KEY
        name: 
awsZone:
  id:
  domainName:
  description: "kuadrant managed zone"

aws:
  accesskey:
  secretAccessKey:

dns:
  routingStrategy: loadbalanced
  loadBalancing:
    geo:
      code: ""       # e.g., "JP" or "KR" per cluster
      default: false # exactly ONE cluster must set true
    weighted:
      defaultWeight: 120
  healthCheck:
    path: /health
    interval: 1m
    failureThreshold: 3

registry:
  password:
  username:
  dockerjson:
